/*
 * Capture the Flag
 *
 * A friendly game of Capture the Flag
 *
 * API version: 1.0.0
 * Contact: hello@testdouble.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package game-client
// Error struct for Error
type Error struct {
	// The HTTP status code
	Code int32 `json:"code"`
	// The error message indicating what the issue is
	Message string `json:"message"`
}
