/*
 * Capture the Flag
 *
 * A friendly game of Capture the Flag
 *
 * API version: 1.0.0
 * Contact: hello@testdouble.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package game_client
// InlineResponse202 struct for InlineResponse202
type InlineResponse202 struct {
	Player Player `json:"player,omitempty"`
	Flag Flag `json:"flag,omitempty"`
	Opponents []Player `json:"opponents,omitempty"`
}
