/*
 * Capture the Flag
 *
 * A friendly game of Capture the Flag
 *
 * API version: 1.0.0
 * Contact: hello@testdouble.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package game_client

// InlineResponse400 struct for InlineResponse400
type InlineResponse400 struct {
	Error Error `json:"error,omitempty"`
}
